version: '2'
services:
    jhipstertest-app:
        image: jhipstertest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstertest-postgresql:5432/jhipstertest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipstertest-elasticsearch:9300
        ports:
            - 8080:8080
    jhipstertest-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstertest-postgresql
    jhipstertest-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipstertest-elasticsearch
